plugins {
    id 'com.android.application'
}

android {
    namespace 'com.pokepixelarena.app'
    compileSdk 33

    defaultConfig {
        applicationId "com.pokepixelarena.app"
        minSdk 21
        targetSdk 33
        versionCode 1
        versionName "1.0"
    }

    signingConfigs {
        release {
            storeFile file("../keystore/release.keystore")
            storePassword "pixelarena"
            keyAlias "arena"
            keyPassword "pixelarena"
        }
    }

    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
